from tutorials import *  # noqa: F403
import tutorials

import pkgutil
import os

# generate RST from python
tests = []
for submodule in pkgutil.walk_packages(tutorials.__path__):
    if submodule.name.startswith("_"):
        continue
    fname = os.path.join(os.path.dirname(__file__), "tutorials", submodule.name) + ".py"
    contents = ".. THIS FILE WAS AUTOGENERATED BY GENERATE_TUTORIALS.PY. ANY CHANGES WILL BE OVERWRITTEN.\n\n"
    block_type = None
    blocks = []
    with open(fname, "r") as f:
        for line in f:
            if line.startswith("## IMAGE"):
                if "ZOOM" in line:
                    imgname = submodule.name + "_zoom.png"
                else:
                    imgname = submodule.name + ".png"
                image_rst = "\n.. image:: " + imgname + "\n"
                if len(blocks) > 0 and blocks[-1][0] == "comment":
                    blocks[-1][1].append(image_rst)
                else:
                    # write out code
                    contents += "\n.. code-block:: python\n   :linenos:\n\n"
                    contents += "".join(blocks[-1][1])
                    contents += "\n"
                    blocks.append(["comment", [image_rst]])
            elif line.startswith("## STOP"):
                if blocks[-1][0] == "code":
                    contents += "\n.. code-block:: python\n   :linenos:\n\n"
                contents += "".join(blocks[-1][1])
                contents += "\n"
                contents += (
                    "\nReference\n---------\n\n.. code-block:: python\n   :linenos:\n\n"
                )
                for block in blocks:
                    if block[0] == "code":
                        contents += "".join(block[1])
                break
            elif line.startswith("#"):
                block_type = "comment"
                if len(blocks) == 0 or block_type != blocks[-1][0]:
                    if len(blocks) > 0:
                        contents += "\n.. code-block:: python\n   :linenos:\n\n"
                        contents += "".join(blocks[-1][1])
                        contents += "\n"
                    blocks.append(["comment", []])
                if line.startswith("# "):
                    blocks[-1][1].append(line[2:])
                else:
                    blocks[-1][1].append(line[1:])
            else:
                block_type = "code"
                if len(blocks) == 0 or block_type != blocks[-1][0]:
                    if len(blocks) > 0:
                        contents += "".join(blocks[-1][1])
                    blocks.append(["code", []])
                blocks[-1][1].append("   " + line)
    rst_fname = (
        os.path.join(
            os.path.dirname(__file__), "tutorials", "generated", submodule.name
        )
        + ".rst"
    )
    with open(rst_fname, "w") as f:
        f.write(contents)
