name: Unit test

on: push

jobs:
  test:
    name: Run unit tests
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Test
      run: python -m unittest discover -v -s test
  lint:
    name: Run black/ruff linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Ruff lint
      uses: astral-sh/ruff-action@v3
    - name: Black lint
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        use_pyproject: true
        version: "25.12"


